version: '3.9'
services:
  chroma:
    image: chromadb/chroma:latest
    volumes:
      - ./chroma-data:/chroma/chroma
    ports:
      - "8000:8000"
    environment:
      - ALLOW_RESET=true
      - CHROMA_DB_IMPL=duckdb+parquet
      - PERSIST_DIRECTORY=/chroma/chroma
    restart: unless-stopped
    networks:
      - rag-network
  
  rag-api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./chroma-data:/app/chroma-data
      - ./.env:/app/.env
    ports:
      - "5000:5000"
    environment:
      - CHROMA_HOST=chroma
      - CHROMA_PORT=8000
    restart: unless-stopped
    depends_on:
      - chroma
    networks:
      - rag-network

networks:
  rag-network:
    driver: bridge